# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\ui_employee_list_widget_small.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_smal_row_Widget(object):
    def setupUi(self, smal_row_Widget):
        smal_row_Widget.setObjectName("smal_row_Widget")
        smal_row_Widget.resize(510, 44)
        smal_row_Widget.setMinimumSize(QtCore.QSize(510, 44))
        smal_row_Widget.setMaximumSize(QtCore.QSize(510, 44))
        smal_row_Widget.setStyleSheet("border:none;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(smal_row_Widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QFrame(smal_row_Widget)
        self.main_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(9, 38, 53);\n"
"border-radius : 5px;\n"
"}\n"
"QLabel{\n"
"color: rgb(255, 255, 255);\n"
"    font:600 11pt \"Montserrat\";\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_2.setContentsMargins(23, 6, 13, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user_name_label = QtWidgets.QLabel(self.main_frame)
        self.user_name_label.setObjectName("user_name_label")
        self.horizontalLayout_2.addWidget(self.user_name_label, 0, QtCore.Qt.AlignVCenter)
        self.user_mail_label = QtWidgets.QLabel(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_mail_label.sizePolicy().hasHeightForWidth())
        self.user_mail_label.setSizePolicy(sizePolicy)
        self.user_mail_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.user_mail_label.setObjectName("user_mail_label")
        self.horizontalLayout_2.addWidget(self.user_mail_label, 0, QtCore.Qt.AlignVCenter)
        self.selected_btn = QtWidgets.QPushButton(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_btn.sizePolicy().hasHeightForWidth())
        self.selected_btn.setSizePolicy(sizePolicy)
        self.selected_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.selected_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(229, 189, 48);\n"
"border-radius : 5px ;\n"
"font: 100 9pt \"Montserrat\";\n"
"padding :5px;\n"
"\n"
"}\n"
":hover{\n"
"background-color: rgb(184, 150, 38);\n"
"}")
        self.selected_btn.setIconSize(QtCore.QSize(25, 25))
        self.selected_btn.setObjectName("selected_btn")
        self.horizontalLayout_2.addWidget(self.selected_btn, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.main_frame)

        self.retranslateUi(smal_row_Widget)
        QtCore.QMetaObject.connectSlotsByName(smal_row_Widget)

    def retranslateUi(self, smal_row_Widget):
        _translate = QtCore.QCoreApplication.translate
        smal_row_Widget.setWindowTitle(_translate("smal_row_Widget", "Form"))
        self.user_name_label.setText(_translate("smal_row_Widget", "usrNAme"))
        self.user_mail_label.setText(_translate("smal_row_Widget", "userMAil"))
        self.selected_btn.setText(_translate("smal_row_Widget", "Seç"))
import image_rc
