# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\ui_employee_info_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inof_emp(object):
    def setupUi(self, inof_emp):
        inof_emp.setObjectName("inof_emp")
        inof_emp.resize(200, 90)
        inof_emp.setMinimumSize(QtCore.QSize(200, 90))
        inof_emp.setMaximumSize(QtCore.QSize(200, 90))
        inof_emp.setStyleSheet("background-color: rgb(7, 26, 35);\n"
"border-radius: 5px;\n"
"color : rgb(255,255,255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(inof_emp)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(inof_emp)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.taskName = QtWidgets.QLabel(self.frame)
        self.taskName.setObjectName("taskName")
        self.horizontalLayout_2.addWidget(self.taskName)
        self.info_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_btn.sizePolicy().hasHeightForWidth())
        self.info_btn.setSizePolicy(sizePolicy)
        self.info_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"paddin:5p;\n"
"}\n"
"\n"
":hover{\n"
"background-color: rgb(20, 69, 93);\n"
"}")
        self.info_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_btn.setIcon(icon)
        self.info_btn.setIconSize(QtCore.QSize(26, 26))
        self.info_btn.setObjectName("info_btn")
        self.horizontalLayout_2.addWidget(self.info_btn)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(inof_emp)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startingDate = QtWidgets.QLabel(self.frame_2)
        self.startingDate.setAlignment(QtCore.Qt.AlignCenter)
        self.startingDate.setObjectName("startingDate")
        self.horizontalLayout.addWidget(self.startingDate)
        self.endDAte = QtWidgets.QLabel(self.frame_2)
        self.endDAte.setAlignment(QtCore.Qt.AlignCenter)
        self.endDAte.setObjectName("endDAte")
        self.horizontalLayout.addWidget(self.endDAte)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(inof_emp)
        QtCore.QMetaObject.connectSlotsByName(inof_emp)

    def retranslateUi(self, inof_emp):
        _translate = QtCore.QCoreApplication.translate
        inof_emp.setWindowTitle(_translate("inof_emp", "Form"))
        self.taskName.setText(_translate("inof_emp", "TaskNAme"))
        self.startingDate.setText(_translate("inof_emp", "startingDate"))
        self.endDAte.setText(_translate("inof_emp", "EndDAte"))
import image_rc
