# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\ui_employee_list_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(710, 60)
        Form.setMinimumSize(QtCore.QSize(710, 60))
        Form.setMaximumSize(QtCore.QSize(111111, 111111))
        Form.setStyleSheet("*{\n"
"background-color: rgb(7, 26, 35);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QFrame(Form)
        self.main_frame.setStyleSheet("#main_frame{\n"
"border-radius : 5px;\n"
"color: rgb(249, 202, 36);\n"
"font: 1000 12pt \"Montserrat\";\n"
"border : 2px outset rgb(16, 16, 16);\n"
"background: rgba(76, 175, 80, 0);\n"
"}\n"
"*{\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 1000 10pt \"Montserrat\";\n"
"}\n"
"")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.employee_name_label = QtWidgets.QLabel(self.main_frame)
        self.employee_name_label.setStyleSheet("background: rgba(76, 175, 80, 0);")
        self.employee_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.employee_name_label.setObjectName("employee_name_label")
        self.horizontalLayout_2.addWidget(self.employee_name_label)
        self.employee_mail_label = QtWidgets.QLabel(self.main_frame)
        self.employee_mail_label.setStyleSheet("background: rgba(76, 175, 80, 0);")
        self.employee_mail_label.setAlignment(QtCore.Qt.AlignCenter)
        self.employee_mail_label.setObjectName("employee_mail_label")
        self.horizontalLayout_2.addWidget(self.employee_mail_label)
        self.select_btn = QtWidgets.QPushButton(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_btn.sizePolicy().hasHeightForWidth())
        self.select_btn.setSizePolicy(sizePolicy)
        self.select_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.select_btn.setStyleSheet("*\n"
"{border:none;\n"
"background-color: rgb(229, 189, 48);\n"
"border-radius :5px;\n"
"padding : 3px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
":hover{\n"
"background-color: rgb(104, 85, 21);\n"
"}")
        self.select_btn.setObjectName("select_btn")
        self.horizontalLayout_2.addWidget(self.select_btn)
        self.horizontalLayout.addWidget(self.main_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.employee_name_label.setText(_translate("Form", "userName"))
        self.employee_mail_label.setText(_translate("Form", "userMail"))
        self.select_btn.setText(_translate("Form", "Seç"))
