# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\ui_list_employee_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListEmployee_Window(object):
    def setupUi(self, ListEmployee_Window):
        ListEmployee_Window.setObjectName("ListEmployee_Window")
        ListEmployee_Window.resize(550, 400)
        ListEmployee_Window.setMinimumSize(QtCore.QSize(550, 400))
        ListEmployee_Window.setMaximumSize(QtCore.QSize(550, 400))
        ListEmployee_Window.setStyleSheet("*{\n"
"background-color: rgb(7, 26, 35);\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 5px;\n"
"\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(ListEmployee_Window)
        self.horizontalLayout.setContentsMargins(6, 6, 10, 6)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QFrame(ListEmployee_Window)
        self.main_frame.setStyleSheet("QFrame#main_frame{\n"
"border : 2px outset rgb(120, 120, 120);\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.main_frame)
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.header = QtWidgets.QLabel(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMaximumSize(QtCore.QSize(250, 16777215))
        self.header.setStyleSheet("*{\n"
"background-color: rgb(9, 38, 53);\n"
"border-radius : 5px;\n"
"padding : 6px;\n"
"    font: 800 12pt \"Montserrat\";\n"
"    color: rgb(229, 189, 48);\n"
"}\n"
"\n"
"")
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.horizontalLayout_2.addWidget(self.header)
        self.exit_btn = QtWidgets.QPushButton(self.header_frame)
        self.exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Ellipse 5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(17, 17))
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout_2.addWidget(self.exit_btn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.header_frame)
        self.employee_list_scrollArea = QtWidgets.QScrollArea(self.main_frame)
        self.employee_list_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.employee_list_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.employee_list_scrollArea.setWidgetResizable(True)
        self.employee_list_scrollArea.setObjectName("employee_list_scrollArea")
        self.employee_List_widget = QtWidgets.QWidget()
        self.employee_List_widget.setGeometry(QtCore.QRect(0, 0, 530, 322))
        self.employee_List_widget.setObjectName("employee_List_widget")
        self.employee_List_widget_layout = QtWidgets.QVBoxLayout(self.employee_List_widget)
        self.employee_List_widget_layout.setObjectName("employee_List_widget_layout")
        self.employee_list_scrollArea.setWidget(self.employee_List_widget)
        self.verticalLayout.addWidget(self.employee_list_scrollArea)
        self.horizontalLayout.addWidget(self.main_frame)

        self.retranslateUi(ListEmployee_Window)
        QtCore.QMetaObject.connectSlotsByName(ListEmployee_Window)

    def retranslateUi(self, ListEmployee_Window):
        _translate = QtCore.QCoreApplication.translate
        ListEmployee_Window.setWindowTitle(_translate("ListEmployee_Window", "Dialog"))
        self.header.setText(_translate("ListEmployee_Window", "ÇALIŞANLAR LİSTESİ"))
import image_rc
