# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\ui_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 335)
        Dialog.setMinimumSize(QtCore.QSize(1000, 335))
        Dialog.setMaximumSize(QtCore.QSize(1000, 335))
        Dialog.setStyleSheet("*{\n"
"background-color: rgb(7, 26, 35);\n"
"color: rgb(255, 255, 255);\n"
"border : none ;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.exit_btn = QtWidgets.QPushButton(self.frame_2)
        self.exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Ellipse 5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(20, 20))
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout_3.addWidget(self.exit_btn, 0, QtCore.Qt.AlignRight)
        self.main_frame = QtWidgets.QFrame(self.frame_2)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.main_frame)
        self.frame.setMinimumSize(QtCore.QSize(140, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(250, 50))
        self.label_2.setMaximumSize(QtCore.QSize(250, 50))
        self.label_2.setStyleSheet("*{\n"
"background-color: rgb(9, 38, 53);\n"
"pading : 6px;\n"
"border-radius:5px;\n"
"font: 1000 14pt \"Montserrat\";\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.logo_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        self.logo_label.setMaximumSize(QtCore.QSize(210, 70))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(":/image/logo.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.logo_label.setWordWrap(False)
        self.logo_label.setIndent(-1)
        self.logo_label.setOpenExternalLinks(False)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_4.addWidget(self.logo_label)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font: 11pt \"Montserrat\";")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        self.main_form_frame = QtWidgets.QFrame(self.main_frame)
        self.main_form_frame.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"width: 20px;\n"
"height: 30px;\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"}\n"
"QLabel{\n"
"font:45 14pt \"MS Shell Dlg 2\";\n"
"text-align: center;\n"
"\n"
"}\n"
"QLineEdit{\n"
"background-color: rgb(20, 69, 93);\n"
"border-radius : 5px;\n"
"padding:5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.main_form_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_form_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_form_frame.setObjectName("main_form_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_form_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 49, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.eposta_frame = QtWidgets.QFrame(self.main_form_frame)
        self.eposta_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.eposta_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.eposta_frame.setObjectName("eposta_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.eposta_frame)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.eposta_label = QtWidgets.QLabel(self.eposta_frame)
        self.eposta_label.setObjectName("eposta_label")
        self.horizontalLayout_2.addWidget(self.eposta_label, 0, QtCore.Qt.AlignHCenter)
        self.eposta_lineedit = QtWidgets.QLineEdit(self.eposta_frame)
        self.eposta_lineedit.setMaximumSize(QtCore.QSize(350, 16777215))
        self.eposta_lineedit.setText("")
        self.eposta_lineedit.setObjectName("eposta_lineedit")
        self.horizontalLayout_2.addWidget(self.eposta_lineedit)
        self.verticalLayout_2.addWidget(self.eposta_frame, 0, QtCore.Qt.AlignBottom)
        self.password_frame = QtWidgets.QFrame(self.main_form_frame)
        self.password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.password_frame.setObjectName("password_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.password_frame)
        self.horizontalLayout_3.setContentsMargins(-1, 25, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.password_label = QtWidgets.QLabel(self.password_frame)
        self.password_label.setObjectName("password_label")
        self.horizontalLayout_3.addWidget(self.password_label, 0, QtCore.Qt.AlignHCenter)
        self.password_lineedit = QtWidgets.QLineEdit(self.password_frame)
        self.password_lineedit.setMaximumSize(QtCore.QSize(350, 16777215))
        self.password_lineedit.setText("")
        self.password_lineedit.setObjectName("password_lineedit")
        self.horizontalLayout_3.addWidget(self.password_lineedit)
        self.verticalLayout_2.addWidget(self.password_frame, 0, QtCore.Qt.AlignTop)
        self.button_row_frame = QtWidgets.QFrame(self.main_form_frame)
        self.button_row_frame.setStyleSheet("border-radius : 5px; \n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.button_row_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_row_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_row_frame.setObjectName("button_row_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.button_row_frame)
        self.horizontalLayout_4.setSpacing(86)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.register_btn = QtWidgets.QPushButton(self.button_row_frame)
        self.register_btn.setMinimumSize(QtCore.QSize(200, 40))
        self.register_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.register_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 66, 114);\n"
"border-radius : 5px ;\n"
"font: 600 12pt \"Montserrat\";\n"
"}\n"
":hover{\n"
"background-color: rgb(9, 33, 44);\n"
"}")
        self.register_btn.setObjectName("register_btn")
        self.horizontalLayout_4.addWidget(self.register_btn)
        self.signin_btn = QtWidgets.QPushButton(self.button_row_frame)
        self.signin_btn.setMinimumSize(QtCore.QSize(200, 40))
        self.signin_btn.setMaximumSize(QtCore.QSize(15, 16777215))
        self.signin_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(33, 164, 62);\n"
"border-radius : 5px ;\n"
"font: 600 12pt \"Montserrat\";\n"
"}\n"
":hover{\n"
"background-color: rgb(25, 126, 47);\n"
"}")
        self.signin_btn.setObjectName("signin_btn")
        self.horizontalLayout_4.addWidget(self.signin_btn)
        self.verticalLayout_2.addWidget(self.button_row_frame)
        self.horizontalLayout.addWidget(self.main_form_frame)
        self.verticalLayout_3.addWidget(self.main_frame)
        self.status_label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setStyleSheet("color: rgb(158, 40, 40);")
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.verticalLayout_3.addWidget(self.status_label, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Hoş Geldiniz"))
        self.label.setText(_translate("Dialog", "Developed by FezaTech v1.0.0"))
        self.eposta_label.setText(_translate("Dialog", "E-POSTA"))
        self.password_label.setText(_translate("Dialog", "ŞİFRE"))
        self.register_btn.setText(_translate("Dialog", "Kayıt Ol"))
        self.signin_btn.setText(_translate("Dialog", "Giriş Yap"))
import image_rc
