# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\ui_project_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskJamProjectInfo(object):
    def setupUi(self, TaskJamProjectInfo):
        TaskJamProjectInfo.setObjectName("TaskJamProjectInfo")
        TaskJamProjectInfo.resize(1000, 388)
        TaskJamProjectInfo.setMinimumSize(QtCore.QSize(1000, 350))
        TaskJamProjectInfo.setMaximumSize(QtCore.QSize(1000, 388))
        TaskJamProjectInfo.setStyleSheet("*{\n"
"font: 1000 12pt \"Montserrat\";\n"
"border : none ;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QWidget#AddTask{\n"
"background-color: rgb(7, 26, 35);\n"
"border-radius : 5px;\n"
"box-shadow: 15px 15px 15px 15px rgb(0, 0, 0);\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}\n"
"QLineEdit{\n"
"background-color: rgb(20, 69, 93);\n"
"border-radius : 5px;\n"
"padding : 3px;\n"
"box-shadow: 15px 15px 15px 15px rgb(0, 0, 0);\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}\n"
"QPushButton{\n"
"box-shadow: 15px 15px 15px 15px rgb(0, 0, 0);\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(TaskJamProjectInfo)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.main_frame = QtWidgets.QFrame(TaskJamProjectInfo)
        self.main_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.main_frame.setStyleSheet("QFrame#main_frame{\n"
"background-color: rgb(7, 26, 35);\n"
"border-radius : 5px;\n"
"box-shadow: 15px 15px 15px 15px rgb(0, 0, 0);\n"
"border : 2px outset rgb(120, 120, 120);\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_4.setContentsMargins(12, 12, 12, 0)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.addProject_header_freame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addProject_header_freame.sizePolicy().hasHeightForWidth())
        self.addProject_header_freame.setSizePolicy(sizePolicy)
        self.addProject_header_freame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addProject_header_freame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addProject_header_freame.setObjectName("addProject_header_freame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.addProject_header_freame)
        self.horizontalLayout.setContentsMargins(0, 7, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_label = QtWidgets.QLabel(self.addProject_header_freame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        self.title_label.setMinimumSize(QtCore.QSize(200, 0))
        self.title_label.setAutoFillBackground(False)
        self.title_label.setStyleSheet("color: rgb(229, 189, 48);\n"
"background-color: rgb(9, 38, 53);\n"
"border-radius : 5px;\n"
"padding : 6px;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        self.winow_btn_frame = QtWidgets.QFrame(self.addProject_header_freame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.winow_btn_frame.sizePolicy().hasHeightForWidth())
        self.winow_btn_frame.setSizePolicy(sizePolicy)
        self.winow_btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.winow_btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.winow_btn_frame.setObjectName("winow_btn_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.winow_btn_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exit_btn = QtWidgets.QPushButton(self.winow_btn_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_btn.sizePolicy().hasHeightForWidth())
        self.exit_btn.setSizePolicy(sizePolicy)
        self.exit_btn.setStyleSheet("border:none;")
        self.exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Ellipse 5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(20, 20))
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout_2.addWidget(self.exit_btn)
        self.horizontalLayout.addWidget(self.winow_btn_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addWidget(self.addProject_header_freame, 0, QtCore.Qt.AlignTop)
        self.addProject_name_frame = QtWidgets.QFrame(self.main_frame)
        self.addProject_name_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addProject_name_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addProject_name_frame.setObjectName("addProject_name_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.addProject_name_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 18)
        self.horizontalLayout_9.setSpacing(25)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.project_name_label = QtWidgets.QLabel(self.addProject_name_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_name_label.sizePolicy().hasHeightForWidth())
        self.project_name_label.setSizePolicy(sizePolicy)
        self.project_name_label.setMinimumSize(QtCore.QSize(170, 0))
        self.project_name_label.setMaximumSize(QtCore.QSize(170, 16777215))
        self.project_name_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.project_name_label.setObjectName("project_name_label")
        self.horizontalLayout_9.addWidget(self.project_name_label, 0, QtCore.Qt.AlignLeft)
        self.project_name_lineEdit = QtWidgets.QLineEdit(self.addProject_name_frame)
        self.project_name_lineEdit.setMinimumSize(QtCore.QSize(240, 0))
        self.project_name_lineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.project_name_lineEdit.setObjectName("project_name_lineEdit")
        self.horizontalLayout_9.addWidget(self.project_name_lineEdit, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_4.addWidget(self.addProject_name_frame, 0, QtCore.Qt.AlignLeft)
        self.addProject_describe_frame = QtWidgets.QFrame(self.main_frame)
        self.addProject_describe_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addProject_describe_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addProject_describe_frame.setObjectName("addProject_describe_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.addProject_describe_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 29)
        self.horizontalLayout_4.setSpacing(24)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.project_describe_title = QtWidgets.QLabel(self.addProject_describe_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_describe_title.sizePolicy().hasHeightForWidth())
        self.project_describe_title.setSizePolicy(sizePolicy)
        self.project_describe_title.setMinimumSize(QtCore.QSize(170, 0))
        self.project_describe_title.setMaximumSize(QtCore.QSize(170, 16777215))
        self.project_describe_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.project_describe_title.setObjectName("project_describe_title")
        self.horizontalLayout_4.addWidget(self.project_describe_title, 0, QtCore.Qt.AlignLeft)
        self.project_describe_lineEdit = QtWidgets.QLineEdit(self.addProject_describe_frame)
        self.project_describe_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.project_describe_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.project_describe_lineEdit.setObjectName("project_describe_lineEdit")
        self.horizontalLayout_4.addWidget(self.project_describe_lineEdit)
        self.verticalLayout_4.addWidget(self.addProject_describe_frame)
        self.addProject_date_row_frame = QtWidgets.QFrame(self.main_frame)
        self.addProject_date_row_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addProject_date_row_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addProject_date_row_frame.setObjectName("addProject_date_row_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.addProject_date_row_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 9)
        self.horizontalLayout_5.setSpacing(18)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.start_date_label = QtWidgets.QLabel(self.addProject_date_row_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_date_label.sizePolicy().hasHeightForWidth())
        self.start_date_label.setSizePolicy(sizePolicy)
        self.start_date_label.setMinimumSize(QtCore.QSize(170, 0))
        self.start_date_label.setMaximumSize(QtCore.QSize(170, 16777215))
        self.start_date_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.start_date_label.setObjectName("start_date_label")
        self.horizontalLayout_5.addWidget(self.start_date_label, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.addProject_date_row_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(7, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.starting_date_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.starting_date_lineEdit.setMinimumSize(QtCore.QSize(240, 0))
        self.starting_date_lineEdit.setMaximumSize(QtCore.QSize(240, 16777215))
        self.starting_date_lineEdit.setText("")
        self.starting_date_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.starting_date_lineEdit.setObjectName("starting_date_lineEdit")
        self.verticalLayout_3.addWidget(self.starting_date_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.format_1 = QtWidgets.QLabel(self.frame_2)
        self.format_1.setStyleSheet("font: 10pt \"Montserrat\";")
        self.format_1.setObjectName("format_1")
        self.verticalLayout_3.addWidget(self.format_1, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_5.addWidget(self.frame_2, 0, QtCore.Qt.AlignLeft)
        self.end_date_label = QtWidgets.QLabel(self.addProject_date_row_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_date_label.sizePolicy().hasHeightForWidth())
        self.end_date_label.setSizePolicy(sizePolicy)
        self.end_date_label.setMinimumSize(QtCore.QSize(150, 0))
        self.end_date_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.end_date_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.end_date_label.setObjectName("end_date_label")
        self.horizontalLayout_5.addWidget(self.end_date_label, 0, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.addProject_date_row_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ending_date_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.ending_date_lineEdit.setMinimumSize(QtCore.QSize(240, 0))
        self.ending_date_lineEdit.setMaximumSize(QtCore.QSize(240, 16777215))
        self.ending_date_lineEdit.setText("")
        self.ending_date_lineEdit.setObjectName("ending_date_lineEdit")
        self.verticalLayout_2.addWidget(self.ending_date_lineEdit, 0, QtCore.Qt.AlignRight)
        self.format_2 = QtWidgets.QLabel(self.frame_3)
        self.format_2.setStyleSheet("font: 10pt \"Montserrat\";")
        self.format_2.setObjectName("format_2")
        self.verticalLayout_2.addWidget(self.format_2, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.verticalLayout_4.addWidget(self.addProject_date_row_frame)
        self.addProject_footer_frame = QtWidgets.QFrame(self.main_frame)
        self.addProject_footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addProject_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addProject_footer_frame.setObjectName("addProject_footer_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.addProject_footer_frame)
        self.horizontalLayout_7.setContentsMargins(-1, -1, 128, -1)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.project_dlete_btn = QtWidgets.QPushButton(self.addProject_footer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_dlete_btn.sizePolicy().hasHeightForWidth())
        self.project_dlete_btn.setSizePolicy(sizePolicy)
        self.project_dlete_btn.setStyleSheet("*{\n"
"background-color: rgb(20, 66, 114);\n"
"border-radius : 5px ;\n"
"font: 600 12pt \"Montserrat\";\n"
"padding : 4px;\n"
"}\n"
":hover{\n"
"background-color: rgb(9, 33, 44);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/garbage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.project_dlete_btn.setIcon(icon1)
        self.project_dlete_btn.setIconSize(QtCore.QSize(20, 20))
        self.project_dlete_btn.setObjectName("project_dlete_btn")
        self.horizontalLayout_7.addWidget(self.project_dlete_btn)
        self.project_add_btn = QtWidgets.QPushButton(self.addProject_footer_frame)
        self.project_add_btn.setMinimumSize(QtCore.QSize(211, 0))
        self.project_add_btn.setMaximumSize(QtCore.QSize(211, 16777215))
        self.project_add_btn.setStyleSheet("QPushButton{\n"
"padding : 6px;\n"
"    background-color: rgb(33, 164, 62);\n"
"border-radius:5px;\n"
"font: 600 12pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 132, 28);\n"
" }")
        self.project_add_btn.setObjectName("project_add_btn")
        self.horizontalLayout_7.addWidget(self.project_add_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.addProject_footer_frame)
        self.status_label = QtWidgets.QLabel(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setStyleSheet("color : rgb(195, 49, 49);")
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.verticalLayout_4.addWidget(self.status_label, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addWidget(self.main_frame)

        self.retranslateUi(TaskJamProjectInfo)
        QtCore.QMetaObject.connectSlotsByName(TaskJamProjectInfo)

    def retranslateUi(self, TaskJamProjectInfo):
        _translate = QtCore.QCoreApplication.translate
        TaskJamProjectInfo.setWindowTitle(_translate("TaskJamProjectInfo", "Dialog"))
        self.title_label.setText(_translate("TaskJamProjectInfo", "PROJE GÖRÜNTÜLE"))
        self.project_name_label.setText(_translate("TaskJamProjectInfo", "Proje Adı :"))
        self.project_describe_title.setText(_translate("TaskJamProjectInfo", "Proje Açıklaması :"))
        self.start_date_label.setText(_translate("TaskJamProjectInfo", "Başlangıç Tarihi :"))
        self.format_1.setText(_translate("TaskJamProjectInfo", "format : (gg.aa.yyyy)           "))
        self.end_date_label.setText(_translate("TaskJamProjectInfo", "Bitiş Tarihi :"))
        self.format_2.setText(_translate("TaskJamProjectInfo", "format : (gg.aa.yyyy)"))
        self.project_dlete_btn.setText(_translate("TaskJamProjectInfo", "Projeyi Sil"))
        self.project_add_btn.setText(_translate("TaskJamProjectInfo", "GÜNCELLE"))
import image_rc
