# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\ui_project_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectWindow(object):
    def setupUi(self, ProjectWindow):
        ProjectWindow.setObjectName("ProjectWindow")
        ProjectWindow.resize(390, 140)
        ProjectWindow.setMinimumSize(QtCore.QSize(390, 140))
        ProjectWindow.setMaximumSize(QtCore.QSize(390, 140))
        ProjectWindow.setStyleSheet("*{\n"
"border : none ;\n"
"border-radius : 5px;\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"Montserrat\";\n"
"}\n"
"QWidget#ProjectWindow{\n"
"background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(7, 26, 35), stop:1 rgb(9, 38, 53));\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(ProjectWindow)
        self.verticalLayout.setContentsMargins(10, 2, 10, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_row = QtWidgets.QFrame(ProjectWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_row.sizePolicy().hasHeightForWidth())
        self.top_row.setSizePolicy(sizePolicy)
        self.top_row.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_row.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_row.setObjectName("top_row")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_row)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.project_name = QtWidgets.QLabel(self.top_row)
        self.project_name.setStyleSheet("font: 1000 11pt \"Montserrat\";")
        self.project_name.setObjectName("project_name")
        self.horizontalLayout_2.addWidget(self.project_name)
        self.date_label = QtWidgets.QLabel(self.top_row)
        self.date_label.setText("")
        self.date_label.setObjectName("date_label")
        self.horizontalLayout_2.addWidget(self.date_label, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.top_row)
        self.project_describe = QtWidgets.QLabel(ProjectWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_describe.sizePolicy().hasHeightForWidth())
        self.project_describe.setSizePolicy(sizePolicy)
        self.project_describe.setStyleSheet("word-wrap: normal;\n"
"word-wrap: break-word;")
        self.project_describe.setObjectName("project_describe")
        self.verticalLayout.addWidget(self.project_describe)
        self.bottom_row_frame = QtWidgets.QFrame(ProjectWindow)
        self.bottom_row_frame.setStyleSheet("QPushButton{\n"
"font:  9pt \"Montserrat\";\n"
"}")
        self.bottom_row_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_row_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_row_frame.setObjectName("bottom_row_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bottom_row_frame)
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.workers_amount_label_2 = QtWidgets.QLabel(self.bottom_row_frame)
        self.workers_amount_label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"Montserrat\";")
        self.workers_amount_label_2.setObjectName("workers_amount_label_2")
        self.horizontalLayout_4.addWidget(self.workers_amount_label_2)
        self.amount_label_2 = QtWidgets.QLabel(self.bottom_row_frame)
        self.amount_label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 1000 9pt \"Montserrat\";")
        self.amount_label_2.setObjectName("amount_label_2")
        self.horizontalLayout_4.addWidget(self.amount_label_2)
        self.select_btn_2 = QtWidgets.QPushButton(self.bottom_row_frame)
        self.select_btn_2.setMinimumSize(QtCore.QSize(0, 20))
        self.select_btn_2.setStyleSheet("background-color: rgb(33, 164, 62);")
        self.select_btn_2.setObjectName("select_btn_2")
        self.horizontalLayout_4.addWidget(self.select_btn_2)
        self.show_btn_2 = QtWidgets.QPushButton(self.bottom_row_frame)
        self.show_btn_2.setMinimumSize(QtCore.QSize(0, 20))
        self.show_btn_2.setStyleSheet("background-color: rgb(7, 26, 35);\n"
"color: rgb(255, 255, 255);")
        self.show_btn_2.setObjectName("show_btn_2")
        self.horizontalLayout_4.addWidget(self.show_btn_2)
        self.verticalLayout.addWidget(self.bottom_row_frame)

        self.retranslateUi(ProjectWindow)
        QtCore.QMetaObject.connectSlotsByName(ProjectWindow)

    def retranslateUi(self, ProjectWindow):
        _translate = QtCore.QCoreApplication.translate
        ProjectWindow.setWindowTitle(_translate("ProjectWindow", "Form"))
        self.project_name.setText(_translate("ProjectWindow", "proje adı"))
        self.project_describe.setText(_translate("ProjectWindow", "....."))
        self.workers_amount_label_2.setText(_translate("ProjectWindow", "Aktif çalışan sayısı :"))
        self.amount_label_2.setText(_translate("ProjectWindow", "."))
        self.select_btn_2.setText(_translate("ProjectWindow", "Seç"))
        self.show_btn_2.setText(_translate("ProjectWindow", "Detaylar"))
