# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\ui_task_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskInfo(object):
    def setupUi(self, TaskInfo):
        TaskInfo.setObjectName("TaskInfo")
        TaskInfo.resize(392, 456)
        TaskInfo.setStyleSheet("*{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(TaskInfo)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.color_corner_frame = QtWidgets.QFrame(TaskInfo)
        self.color_corner_frame.setStyleSheet("QFrame#color_corner_frame{\n"
"background-color: rgb(9, 38, 53);\n"
"border-radius:5px;\n"
"font: 600 10pt \"Montserrat\";\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}")
        self.color_corner_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.color_corner_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.color_corner_frame.setObjectName("color_corner_frame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.color_corner_frame)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(14)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.task_detail_header_frame = QtWidgets.QFrame(self.color_corner_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_detail_header_frame.sizePolicy().hasHeightForWidth())
        self.task_detail_header_frame.setSizePolicy(sizePolicy)
        self.task_detail_header_frame.setStyleSheet("*{\n"
"background-color: rgb(9, 38, 53);\n"
"}")
        self.task_detail_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.task_detail_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.task_detail_header_frame.setObjectName("task_detail_header_frame")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.task_detail_header_frame)
        self.horizontalLayout_22.setSpacing(15)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_2 = QtWidgets.QLabel(self.task_detail_header_frame)
        self.label_2.setMinimumSize(QtCore.QSize(9, 36))
        self.label_2.setMaximumSize(QtCore.QSize(9, 36))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/icons/yellow_set_big.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_22.addWidget(self.label_2)
        self.frame_8 = QtWidgets.QFrame(self.task_detail_header_frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.taskdt_name_label = QtWidgets.QLabel(self.frame_8)
        self.taskdt_name_label.setStyleSheet("font: 805 11pt \"Montserrat\";")
        self.taskdt_name_label.setObjectName("taskdt_name_label")
        self.verticalLayout_19.addWidget(self.taskdt_name_label)
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_19.addWidget(self.label_4)
        self.horizontalLayout_22.addWidget(self.frame_8)
        self.taskdt_exit_btn = QtWidgets.QPushButton(self.task_detail_header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskdt_exit_btn.sizePolicy().hasHeightForWidth())
        self.taskdt_exit_btn.setSizePolicy(sizePolicy)
        self.taskdt_exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/exit_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.taskdt_exit_btn.setIcon(icon)
        self.taskdt_exit_btn.setIconSize(QtCore.QSize(40, 40))
        self.taskdt_exit_btn.setObjectName("taskdt_exit_btn")
        self.horizontalLayout_22.addWidget(self.taskdt_exit_btn)
        self.verticalLayout_20.addWidget(self.task_detail_header_frame)
        self.task_detail_body_frame = QtWidgets.QFrame(self.color_corner_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_detail_body_frame.sizePolicy().hasHeightForWidth())
        self.task_detail_body_frame.setSizePolicy(sizePolicy)
        self.task_detail_body_frame.setStyleSheet("*{\n"
"background-color: rgb(9, 38, 53);\n"
"}")
        self.task_detail_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.task_detail_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.task_detail_body_frame.setObjectName("task_detail_body_frame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.task_detail_body_frame)
        self.verticalLayout_21.setContentsMargins(10, 0, 10, -1)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_2 = QtWidgets.QFrame(self.task_detail_body_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_25.setSpacing(20)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(90, 0))
        self.label_11.setStyleSheet("*{\n"
"font: 600 10pt \"Montserrat\";\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_25.addWidget(self.label_11)
        self.taskdt_desk_labell = QtWidgets.QLabel(self.frame_2)
        self.taskdt_desk_labell.setMinimumSize(QtCore.QSize(0, 0))
        self.taskdt_desk_labell.setMaximumSize(QtCore.QSize(400, 24055))
        self.taskdt_desk_labell.setTextFormat(QtCore.Qt.AutoText)
        self.taskdt_desk_labell.setScaledContents(False)
        self.taskdt_desk_labell.setWordWrap(True)
        self.taskdt_desk_labell.setObjectName("taskdt_desk_labell")
        self.horizontalLayout_25.addWidget(self.taskdt_desk_labell)
        self.verticalLayout_21.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.task_detail_body_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_23.setSpacing(20)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_7 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(90, 0))
        self.label_7.setStyleSheet("*{\n"
"font: 600 10pt \"Montserrat\";\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_23.addWidget(self.label_7)
        self.taskdt_emp_name_label = QtWidgets.QLabel(self.frame)
        self.taskdt_emp_name_label.setMinimumSize(QtCore.QSize(0, 0))
        self.taskdt_emp_name_label.setMaximumSize(QtCore.QSize(400, 24055))
        self.taskdt_emp_name_label.setTextFormat(QtCore.Qt.AutoText)
        self.taskdt_emp_name_label.setScaledContents(False)
        self.taskdt_emp_name_label.setWordWrap(True)
        self.taskdt_emp_name_label.setObjectName("taskdt_emp_name_label")
        self.horizontalLayout_23.addWidget(self.taskdt_emp_name_label)
        self.verticalLayout_21.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(self.task_detail_body_frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_26.setSpacing(20)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(90, 0))
        self.label_12.setStyleSheet("*{\n"
"font: 600 10pt \"Montserrat\";\n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_26.addWidget(self.label_12)
        self.taskdt_starting_date_label = QtWidgets.QLabel(self.frame_6)
        self.taskdt_starting_date_label.setMinimumSize(QtCore.QSize(0, 0))
        self.taskdt_starting_date_label.setMaximumSize(QtCore.QSize(400, 24055))
        self.taskdt_starting_date_label.setTextFormat(QtCore.Qt.AutoText)
        self.taskdt_starting_date_label.setScaledContents(False)
        self.taskdt_starting_date_label.setWordWrap(True)
        self.taskdt_starting_date_label.setObjectName("taskdt_starting_date_label")
        self.horizontalLayout_26.addWidget(self.taskdt_starting_date_label)
        self.verticalLayout_21.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.task_detail_body_frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_27.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_27.setSpacing(20)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(90, 0))
        self.label_13.setStyleSheet("*{\n"
"font: 600 10pt \"Montserrat\";\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_27.addWidget(self.label_13)
        self.taskdt_end_Dare_label = QtWidgets.QLabel(self.frame_7)
        self.taskdt_end_Dare_label.setMinimumSize(QtCore.QSize(0, 0))
        self.taskdt_end_Dare_label.setMaximumSize(QtCore.QSize(400, 24055))
        self.taskdt_end_Dare_label.setTextFormat(QtCore.Qt.AutoText)
        self.taskdt_end_Dare_label.setScaledContents(False)
        self.taskdt_end_Dare_label.setWordWrap(True)
        self.taskdt_end_Dare_label.setObjectName("taskdt_end_Dare_label")
        self.horizontalLayout_27.addWidget(self.taskdt_end_Dare_label)
        self.verticalLayout_21.addWidget(self.frame_7)
        self.verticalLayout_20.addWidget(self.task_detail_body_frame)
        self.task_detail_alert_frame = QtWidgets.QFrame(self.color_corner_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_detail_alert_frame.sizePolicy().hasHeightForWidth())
        self.task_detail_alert_frame.setSizePolicy(sizePolicy)
        self.task_detail_alert_frame.setStyleSheet("*{\n"
"background-color: rgb(9, 38, 53);\n"
"}")
        self.task_detail_alert_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.task_detail_alert_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.task_detail_alert_frame.setObjectName("task_detail_alert_frame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.task_detail_alert_frame)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(5)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_3 = QtWidgets.QLabel(self.task_detail_alert_frame)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/icons/red_set_horiontal_big.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_22.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.task_detail_alert_frame)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_22.addWidget(self.label_6)
        self.las_day_for_end = QtWidgets.QLabel(self.task_detail_alert_frame)
        self.las_day_for_end.setStyleSheet("*{\n"
"font: 600 10pt \"Montserrat\";\n"
"}\n"
"")
        self.las_day_for_end.setAlignment(QtCore.Qt.AlignCenter)
        self.las_day_for_end.setObjectName("las_day_for_end")
        self.verticalLayout_22.addWidget(self.las_day_for_end)
        self.verticalLayout_20.addWidget(self.task_detail_alert_frame, 0, QtCore.Qt.AlignHCenter)
        self.task_detail_footer_frame = QtWidgets.QFrame(self.color_corner_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_detail_footer_frame.sizePolicy().hasHeightForWidth())
        self.task_detail_footer_frame.setSizePolicy(sizePolicy)
        self.task_detail_footer_frame.setStyleSheet("*{\n"
"background-color: rgb(9, 38, 53);\n"
"}")
        self.task_detail_footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.task_detail_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.task_detail_footer_frame.setObjectName("task_detail_footer_frame")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.task_detail_footer_frame)
        self.horizontalLayout_28.setSpacing(27)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.taskdt_delete_btn = QtWidgets.QPushButton(self.task_detail_footer_frame)
        self.taskdt_delete_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.taskdt_delete_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.taskdt_delete_btn.setStyleSheet("*{\n"
"padding : 5px;\n"
"border-radius:5px;\n"
"background-color: rgb(193, 0, 0);\n"
"font: 600 10pt \"Montserrat\";\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}\n"
":hover{\n"
"background-color: rgb(147, 0, 0);\n"
"}\n"
"")
        self.taskdt_delete_btn.setObjectName("taskdt_delete_btn")
        self.horizontalLayout_28.addWidget(self.taskdt_delete_btn)
        self.taskdt_edit_btn = QtWidgets.QPushButton(self.task_detail_footer_frame)
        self.taskdt_edit_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.taskdt_edit_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.taskdt_edit_btn.setStyleSheet("*{\n"
"padding : 5px;\n"
"border-radius:5px;\n"
"background-color:rgb(7, 26, 35);\n"
"font: 600 10pt \"Montserrat\";\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}\n"
"\n"
":hover{\n"
"background-color: rgb(18, 69, 93);\n"
"}\n"
"")
        self.taskdt_edit_btn.setObjectName("taskdt_edit_btn")
        self.horizontalLayout_28.addWidget(self.taskdt_edit_btn)
        self.taskdt_done_btn = QtWidgets.QPushButton(self.task_detail_footer_frame)
        self.taskdt_done_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.taskdt_done_btn.setStyleSheet("*{\n"
"padding : 5px;\n"
"border-radius:5px;\n"
"background-color: rgb(33, 164, 62);\n"
"font: 600 10pt \"Montserrat\";\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}\n"
":hover{\n"
"background-color: rgb(21, 107, 40);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.taskdt_done_btn.setIcon(icon1)
        self.taskdt_done_btn.setIconSize(QtCore.QSize(20, 20))
        self.taskdt_done_btn.setAutoRepeat(False)
        self.taskdt_done_btn.setDefault(False)
        self.taskdt_done_btn.setFlat(False)
        self.taskdt_done_btn.setObjectName("taskdt_done_btn")
        self.horizontalLayout_28.addWidget(self.taskdt_done_btn)
        self.verticalLayout_20.addWidget(self.task_detail_footer_frame, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.color_corner_frame)

        self.retranslateUi(TaskInfo)
        QtCore.QMetaObject.connectSlotsByName(TaskInfo)

    def retranslateUi(self, TaskInfo):
        _translate = QtCore.QCoreApplication.translate
        TaskInfo.setWindowTitle(_translate("TaskInfo", "Form"))
        self.taskdt_name_label.setText(_translate("TaskInfo", "TaskName"))
        self.label_4.setText(_translate("TaskInfo", "Görev Detayları"))
        self.label_11.setText(_translate("TaskInfo", "Görev\n"
"Açıklaması"))
        self.taskdt_desk_labell.setText(_translate("TaskInfo", "aa"))
        self.label_7.setText(_translate("TaskInfo", "Çalışan"))
        self.taskdt_emp_name_label.setText(_translate("TaskInfo", "aa"))
        self.label_12.setText(_translate("TaskInfo", "Başlangıç\n"
"Tarihi"))
        self.taskdt_starting_date_label.setText(_translate("TaskInfo", "aa"))
        self.label_13.setText(_translate("TaskInfo", "Bitiş\n"
"Tarihi"))
        self.taskdt_end_Dare_label.setText(_translate("TaskInfo", "aa"))
        self.label_6.setText(_translate("TaskInfo", "Görevin Bitmesine"))
        self.las_day_for_end.setText(_translate("TaskInfo", "TextLabel"))
        self.taskdt_delete_btn.setText(_translate("TaskInfo", "Görevi\n"
"Sil"))
        self.taskdt_edit_btn.setText(_translate("TaskInfo", "Görevi\n"
"Düzenle"))
        self.taskdt_done_btn.setText(_translate("TaskInfo", "Tamamlandı\n"
"Olarak İşaretle"))
import image_rc
