# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\ui_task_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskEdit(object):
    def setupUi(self, TaskEdit):
        TaskEdit.setObjectName("TaskEdit")
        TaskEdit.resize(430, 533)
        TaskEdit.setStyleSheet("*{\n"
"color: rgb(255, 255, 255);\n"
"border : none;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(TaskEdit)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.color_corner_frame = QtWidgets.QFrame(TaskEdit)
        self.color_corner_frame.setStyleSheet("QFrame#color_corner_frame{\n"
"background-color: rgb(9, 38, 53);\n"
"border-radius:5px;\n"
"font: 600 10pt \"Montserrat\";\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}")
        self.color_corner_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.color_corner_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.color_corner_frame.setObjectName("color_corner_frame")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.color_corner_frame)
        self.verticalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_46.setSpacing(6)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.task_detail_header_frame = QtWidgets.QFrame(self.color_corner_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_detail_header_frame.sizePolicy().hasHeightForWidth())
        self.task_detail_header_frame.setSizePolicy(sizePolicy)
        self.task_detail_header_frame.setStyleSheet("*{\n"
"background-color: rgb(9, 38, 53);\n"
"}")
        self.task_detail_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.task_detail_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.task_detail_header_frame.setObjectName("task_detail_header_frame")
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout(self.task_detail_header_frame)
        self.horizontalLayout_71.setSpacing(15)
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.label_51 = QtWidgets.QLabel(self.task_detail_header_frame)
        self.label_51.setMinimumSize(QtCore.QSize(9, 36))
        self.label_51.setMaximumSize(QtCore.QSize(9, 36))
        self.label_51.setText("")
        self.label_51.setPixmap(QtGui.QPixmap(":/icons/icons/yellow_set_big.png"))
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_71.addWidget(self.label_51)
        self.frame_39 = QtWidgets.QFrame(self.task_detail_header_frame)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.taskdt_name_label = QtWidgets.QLabel(self.frame_39)
        self.taskdt_name_label.setStyleSheet("font: 805 11pt \"Montserrat\";")
        self.taskdt_name_label.setObjectName("taskdt_name_label")
        self.verticalLayout_47.addWidget(self.taskdt_name_label)
        self.label_52 = QtWidgets.QLabel(self.frame_39)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_47.addWidget(self.label_52)
        self.horizontalLayout_71.addWidget(self.frame_39)
        self.taskdt_exit_btn = QtWidgets.QPushButton(self.task_detail_header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskdt_exit_btn.sizePolicy().hasHeightForWidth())
        self.taskdt_exit_btn.setSizePolicy(sizePolicy)
        self.taskdt_exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/exit_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.taskdt_exit_btn.setIcon(icon)
        self.taskdt_exit_btn.setIconSize(QtCore.QSize(40, 40))
        self.taskdt_exit_btn.setObjectName("taskdt_exit_btn")
        self.horizontalLayout_71.addWidget(self.taskdt_exit_btn)
        self.verticalLayout_46.addWidget(self.task_detail_header_frame)
        self.task_edit_pageView = QtWidgets.QStackedWidget(self.color_corner_frame)
        self.task_edit_pageView.setStyleSheet("*{\n"
"background-color: rgb(9, 38, 53);\n"
"}")
        self.task_edit_pageView.setObjectName("task_edit_pageView")
        self.edit_page = QtWidgets.QWidget()
        self.edit_page.setObjectName("edit_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.edit_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.task_detail_body_frame = QtWidgets.QFrame(self.edit_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_detail_body_frame.sizePolicy().hasHeightForWidth())
        self.task_detail_body_frame.setSizePolicy(sizePolicy)
        self.task_detail_body_frame.setStyleSheet("*{\n"
"background-color: rgb(9, 38, 53);\n"
"}\n"
"QLineEdit{\n"
"background-color: rgb(7, 26, 35);\n"
"border-radius : 5px;\n"
"padding:5px;\n"
"color : rgb(255, 255, 255);\n"
"}")
        self.task_detail_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.task_detail_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.task_detail_body_frame.setObjectName("task_detail_body_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.task_detail_body_frame)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_44 = QtWidgets.QFrame(self.task_detail_body_frame)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout(self.frame_44)
        self.horizontalLayout_77.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_77.setSpacing(20)
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.label_57 = QtWidgets.QLabel(self.frame_44)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        self.label_57.setMinimumSize(QtCore.QSize(90, 0))
        self.label_57.setStyleSheet("*{\n"
"font: 600 10pt \"Montserrat\";\n"
"}\n"
"")
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_77.addWidget(self.label_57)
        self.task_edit_name_lineedit = QtWidgets.QLineEdit(self.frame_44)
        self.task_edit_name_lineedit.setObjectName("task_edit_name_lineedit")
        self.horizontalLayout_77.addWidget(self.task_edit_name_lineedit)
        self.verticalLayout.addWidget(self.frame_44)
        self.frame_40 = QtWidgets.QFrame(self.task_detail_body_frame)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_72.setSpacing(20)
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.label_53 = QtWidgets.QLabel(self.frame_40)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setMinimumSize(QtCore.QSize(90, 0))
        self.label_53.setStyleSheet("*{\n"
"font: 600 10pt \"Montserrat\";\n"
"}\n"
"")
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_72.addWidget(self.label_53)
        self.task_edit_desc_lineedit = QtWidgets.QLineEdit(self.frame_40)
        self.task_edit_desc_lineedit.setObjectName("task_edit_desc_lineedit")
        self.horizontalLayout_72.addWidget(self.task_edit_desc_lineedit)
        self.verticalLayout.addWidget(self.frame_40)
        self.frame_41 = QtWidgets.QFrame(self.task_detail_body_frame)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout(self.frame_41)
        self.horizontalLayout_73.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_73.setSpacing(20)
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.label_54 = QtWidgets.QLabel(self.frame_41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_54.setMinimumSize(QtCore.QSize(90, 0))
        self.label_54.setStyleSheet("*{\n"
"font: 600 10pt \"Montserrat\";\n"
"}\n"
"")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_73.addWidget(self.label_54)
        self.task_edit_emp_name_label = QtWidgets.QLabel(self.frame_41)
        self.task_edit_emp_name_label.setStyleSheet("*{\n"
"background-color: rgb(9, 38, 53);\n"
"}\n"
"QLabel{\n"
"background-color: rgb(7, 26, 35);\n"
"border-radius : 5px;\n"
"padding:5px;\n"
"color : rgb(255, 255, 255);\n"
"}")
        self.task_edit_emp_name_label.setText("")
        self.task_edit_emp_name_label.setObjectName("task_edit_emp_name_label")
        self.horizontalLayout_73.addWidget(self.task_edit_emp_name_label)
        self.task_edit_emp_select_btn = QtWidgets.QPushButton(self.frame_41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_edit_emp_select_btn.sizePolicy().hasHeightForWidth())
        self.task_edit_emp_select_btn.setSizePolicy(sizePolicy)
        self.task_edit_emp_select_btn.setStyleSheet("*{\n"
"background-color: rgb(229, 189, 48);\n"
"color : rgb(0, 0, 0);\n"
"border-radius:5px;\n"
"padding :5px;\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}\n"
":hover{\n"
"background-color: rgb(185, 151, 38);\n"
"color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/paperclip.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.task_edit_emp_select_btn.setIcon(icon1)
        self.task_edit_emp_select_btn.setObjectName("task_edit_emp_select_btn")
        self.horizontalLayout_73.addWidget(self.task_edit_emp_select_btn)
        self.verticalLayout.addWidget(self.frame_41)
        self.frame_42 = QtWidgets.QFrame(self.task_detail_body_frame)
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout(self.frame_42)
        self.horizontalLayout_74.setSpacing(20)
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.label_55 = QtWidgets.QLabel(self.frame_42)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setMinimumSize(QtCore.QSize(90, 0))
        self.label_55.setStyleSheet("*{\n"
"font: 600 10pt \"Montserrat\";\n"
"}\n"
"")
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_74.addWidget(self.label_55)
        self.task_edit_start_date_lineedit = QtWidgets.QLineEdit(self.frame_42)
        self.task_edit_start_date_lineedit.setObjectName("task_edit_start_date_lineedit")
        self.horizontalLayout_74.addWidget(self.task_edit_start_date_lineedit)
        self.verticalLayout.addWidget(self.frame_42)
        self.frame_43 = QtWidgets.QFrame(self.task_detail_body_frame)
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout(self.frame_43)
        self.horizontalLayout_75.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_75.setSpacing(20)
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.label_56 = QtWidgets.QLabel(self.frame_43)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setMinimumSize(QtCore.QSize(90, 0))
        self.label_56.setStyleSheet("*{\n"
"font: 600 10pt \"Montserrat\";\n"
"}\n"
"")
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_75.addWidget(self.label_56)
        self.task_edit_end_date_lineedit = QtWidgets.QLineEdit(self.frame_43)
        self.task_edit_end_date_lineedit.setObjectName("task_edit_end_date_lineedit")
        self.horizontalLayout_75.addWidget(self.task_edit_end_date_lineedit)
        self.verticalLayout.addWidget(self.frame_43)
        self.verticalLayout_2.addWidget(self.task_detail_body_frame)
        self.task_edit_pageView.addWidget(self.edit_page)
        self.emp_list_page = QtWidgets.QWidget()
        self.emp_list_page.setObjectName("emp_list_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.emp_list_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.emp_list_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("*{\n"
"font: 10pt \"Montserrat\";\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.emp_list_window_scrolArea = QtWidgets.QScrollArea(self.emp_list_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emp_list_window_scrolArea.sizePolicy().hasHeightForWidth())
        self.emp_list_window_scrolArea.setSizePolicy(sizePolicy)
        self.emp_list_window_scrolArea.setStyleSheet("")
        self.emp_list_window_scrolArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.emp_list_window_scrolArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.emp_list_window_scrolArea.setWidgetResizable(True)
        self.emp_list_window_scrolArea.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.emp_list_window_scrolArea.setObjectName("emp_list_window_scrolArea")
        self.emp_list_scroll_frame = QtWidgets.QWidget()
        self.emp_list_scroll_frame.setGeometry(QtCore.QRect(0, 0, 426, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emp_list_scroll_frame.sizePolicy().hasHeightForWidth())
        self.emp_list_scroll_frame.setSizePolicy(sizePolicy)
        self.emp_list_scroll_frame.setObjectName("emp_list_scroll_frame")
        self.emp_list_scroll_frame_layout = QtWidgets.QVBoxLayout(self.emp_list_scroll_frame)
        self.emp_list_scroll_frame_layout.setObjectName("emp_list_scroll_frame_layout")
        self.emp_list_window_scrolArea.setWidget(self.emp_list_scroll_frame)
        self.verticalLayout_3.addWidget(self.emp_list_window_scrolArea)
        self.task_edit_pageView.addWidget(self.emp_list_page)
        self.verticalLayout_46.addWidget(self.task_edit_pageView)
        self.working_edit_status_label = QtWidgets.QLabel(self.color_corner_frame)
        self.working_edit_status_label.setStyleSheet("*{\n"
"background-color: none;\n"
"    font: 600 9pt \"Montserrat\";\n"
"    color: rgb(193, 0, 0);\n"
"}")
        self.working_edit_status_label.setText("")
        self.working_edit_status_label.setObjectName("working_edit_status_label")
        self.verticalLayout_46.addWidget(self.working_edit_status_label, 0, QtCore.Qt.AlignHCenter)
        self.task_detail_footer_frame = QtWidgets.QFrame(self.color_corner_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_detail_footer_frame.sizePolicy().hasHeightForWidth())
        self.task_detail_footer_frame.setSizePolicy(sizePolicy)
        self.task_detail_footer_frame.setStyleSheet("*{\n"
"background-color: rgb(9, 38, 53);\n"
"}")
        self.task_detail_footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.task_detail_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.task_detail_footer_frame.setObjectName("task_detail_footer_frame")
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout(self.task_detail_footer_frame)
        self.horizontalLayout_76.setSpacing(27)
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.taskdt_back_btn = QtWidgets.QPushButton(self.task_detail_footer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskdt_back_btn.sizePolicy().hasHeightForWidth())
        self.taskdt_back_btn.setSizePolicy(sizePolicy)
        self.taskdt_back_btn.setMinimumSize(QtCore.QSize(0, 120))
        self.taskdt_back_btn.setMaximumSize(QtCore.QSize(1677777, 16777215))
        self.taskdt_back_btn.setStyleSheet("*{\n"
"padding : 5px;\n"
"border-radius:5px;\n"
"background-color:rgb(7, 26, 35);\n"
"font: 600 10pt \"Montserrat\";\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}\n"
"\n"
":hover{\n"
"background-color: rgb(18, 69, 93);\n"
"}\n"
"")
        self.taskdt_back_btn.setObjectName("taskdt_back_btn")
        self.horizontalLayout_76.addWidget(self.taskdt_back_btn)
        self.taskdt_done_btn = QtWidgets.QPushButton(self.task_detail_footer_frame)
        self.taskdt_done_btn.setMinimumSize(QtCore.QSize(0, 120))
        self.taskdt_done_btn.setStyleSheet("*{\n"
"padding : 5px;\n"
"border-radius:5px;\n"
"background-color: rgb(33, 164, 62);\n"
"font: 600 10pt \"Montserrat\";\n"
"border : 2px outset rgb(16, 16, 16);\n"
"}\n"
":hover{\n"
"background-color: rgb(21, 107, 40);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.taskdt_done_btn.setIcon(icon2)
        self.taskdt_done_btn.setIconSize(QtCore.QSize(20, 20))
        self.taskdt_done_btn.setAutoRepeat(False)
        self.taskdt_done_btn.setDefault(False)
        self.taskdt_done_btn.setFlat(False)
        self.taskdt_done_btn.setObjectName("taskdt_done_btn")
        self.horizontalLayout_76.addWidget(self.taskdt_done_btn)
        self.verticalLayout_46.addWidget(self.task_detail_footer_frame, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.color_corner_frame)

        self.retranslateUi(TaskEdit)
        self.task_edit_pageView.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TaskEdit)

    def retranslateUi(self, TaskEdit):
        _translate = QtCore.QCoreApplication.translate
        TaskEdit.setWindowTitle(_translate("TaskEdit", "Form"))
        self.taskdt_name_label.setText(_translate("TaskEdit", "TaskName"))
        self.label_52.setText(_translate("TaskEdit", "Görev Detayları"))
        self.label_57.setText(_translate("TaskEdit", "Görev\n"
"Adı"))
        self.label_53.setText(_translate("TaskEdit", "Görev\n"
"Açıklaması"))
        self.label_54.setText(_translate("TaskEdit", "Çalışan"))
        self.task_edit_emp_select_btn.setText(_translate("TaskEdit", "SEÇ"))
        self.label_55.setText(_translate("TaskEdit", "Başlangıç\n"
"Tarihi"))
        self.label_56.setText(_translate("TaskEdit", "Bitiş\n"
"Tarihi"))
        self.label.setText(_translate("TaskEdit", "ÇALIŞANLAR LİSTESİ"))
        self.taskdt_back_btn.setText(_translate("TaskEdit", "GERİ\n"
"AL"))
        self.taskdt_done_btn.setText(_translate("TaskEdit", "KAYDET"))
import image_rc
